server:
  port: 8070

spring:
  application:
    name: mall-gateway
#  main:
#    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 3.150.39.20:8848
        ip: 168.5.59.205 # public local net, needs to be modified constantly
        port: 8070
    gateway:
      routes:
        #         ware
        - id: ware_route
          uri: lb://mall-ware
          predicates:
            - Path=/renren-fast/ware/**
          filters:
            - RewritePath=/renren-fast/(?<segment>/?.*), /$\{segment}
        #         member
        - id: member_route
          uri: lb://mall-member
          predicates:
            - Path=/renren-fast/member/**
          filters:
            - RewritePath=/renren-fast/(?<segment>/?.*), /$\{segment}
#         product
        - id: product_route
          uri: lb://mall-product
          predicates:
            - Path=/renren-fast/product/**
          filters:
            - RewritePath=/renren-fast/(?<segment>/?.*), /$\{segment}
#          aws s3
        - id: third_route
          uri: lb://mall-third-party
          predicates:
            - Path=/renren-fast/third/**
          filters:
            - RewritePath=/renren-fast/(?<segment>/?.*), /$\{segment}

        #         login
        - id: app_route
          uri: lb://renren-fast
          predicates:
            - Path=/renren-fast/**
          filters:
            - RewritePath=/renren-fast/(?<segment>/?.*), /renren-fast/$\{segment}