server:
  port: 8070

spring:
  application:
    name: mall-gateway
#  main:
#    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 3.150.39.20:8848
        ip: 168.4.86.146 # public local net, needs to be modified constantly
        port: 8070
    gateway:
      routes:
        - id: route1
          uri: http://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: route2
          uri: http://www.jd.com
          predicates:
            - Query=url,jd



