server:
    port: 8090

spring:
    datasource:
        url: jdbc:mysql://3.150.39.20:3306/mall-pms?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    application:
        name: mall-third-party
    cloud:
        nacos:
            discovery:
                server-addr: 3.150.39.20:8848
                ip: 168.4.75.127 # public local net, needs to be modified constantly
                port: 8090
        aws:
            region:
                static: us-east-2
            credentials:
                access-key: AKIA3B6DKZEMJASA7D4S
                secret-key: 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
            s3:
                bucket: e-mall-files

