server:
    port: 8040

spring:
    datasource:
        url: jdbc:mysql://192.168.101.65:3306/mall-pms?useSSL=false&serverTimezone=UTC
        username: root
        password: 123456
        driver-class-name: com.mysql.cj.jdbc.Driver
    cloud:
        nacos:
            discovery:
                server-addr: 192.168.101.65:8848
#                ip: 168.4.77.36 # public local net, needs to be modified constantly
                port: 8040
        aws:
            region:
                static: us-east-2
            credentials:
                access-key: --
                secret-key: --
            s3:
                bucket: e-mall-files
    application:
        name: mall-product

mybatis-plus:
    mapper-locations: classpath*:/mapper/**/*.xml
    global-config:
        db-config:
            id-type: auto
            logic-delete-value: 1
            logic-not-delete-value: 0


